baseurl: "https://ypg-data.github.io/"
languageCode: "en-us"
title: "YPG Data"
metaDataFormat: "yaml"
theme: "casper"

permalinks:
  post: /post/:year/:month/:title/

params:
  cover: "images/ypg-data.jpg"
  customHeaderPartial: "customHeaderPartial.html"
  githubName: ypg-data
  googleAnalyticsUserID: "UA-80920872-1"

menu:
  main:
    - name: "Home"
      weight: -120
      identifier: "home"
      url: "/"
